apiVersion: v1
kind: Service
metadata:
  name: k8s-nginx
spec:
  selector:
    app: k8s-nginx
  type: LoadBalancer
  ports:
  - port: 3333
    targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-nginx
  template:
    metadata:
      labels:
        app: k8s-nginx
    spec:
      containers:
      - name: k8s-nginx
        image: vishnu1001/k8s-nginx
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000